baseURL = 'https://eastblocktest.pages.dev'
languageCode = 'en-us'
title = 'East Block Ultimate'
theme = "ananke"

[params]
  site_logo = "images/logo50px.png"
  favicon = "images/favicon2.jpeg"
  featured_image = "images/nationals2023.png"
  ananke_socials = [
    { name = "instagram", url = "https://www.instagram.com/eb_ultimate/", label = "East Block"},
  ]
  custom_css = ["custom.scss"]

[[menu.main]]
  identifier = "_index"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "eucf2024/_index"
  name = "EUCF 2024"
  url = "/eucf2024/"
  weight = 2

[[menu.main]]
  identifier = "news/_index"
  name = "News"
  url = "/news/"
  weight = 3

[[menu.main]]
  identifier = "about/_index"
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  identifier = "team/_index"
  name = "Team"
  url = "/team"
  weight = 5

[[menu.main]]
  identifier = "contact/_index"
  name = "Contact"
  url = "/contact"
  weight = 6

# for brands
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
# load all icons except brands
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
# regular icons font family
[[params.plugins.css]]
link = "plugins/font-awesome/v6/regular.css"
# solid icons font family
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/icons/font-awesome"