baseURL = 'https://eastblocktest.pages.dev'
languageCode = 'en-us'
title = 'East Block Ultimate'
theme = "ananke"

[params]
  site_logo = "images/logo50px.png"
  featured_image = "images/nationals2023.png"
  ananke_socials = [
    { name = "instagram", url = "https://www.instagram.com/eb_ultimate/", label = "East Block"},
  ]

[[menu.main]]
  identifier = "_index"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "eucf2024/_index"
  name = "Road to EUCF 2024"
  url = "/eucf2024/"
  weight = 2

[[menu.main]]
  identifier = "news/_index"
  name = "News"
  url = "/news/"
  weight = 3

[[menu.main]]
  identifier = "about/_index"
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  identifier = "team/_index"
  name = "Team"
  url = "/team"
  weight = 5

[[menu.main]]
  identifier = "contact/_index"
  name = "Contact"
  url = "/contact"
  weight = 6